### ISSUE TITLE
Cannot install pkgbuild 1.2.0 during CI of a package that passes checks locally

### ISSUE THREAD

**Issue by amarquard** [r-lib/pkgbuild#111]
I maintain an internal R package, that has a CI trigger on github.
The CI started to fail at this step `devtools::install(upgrade_dependencies = FALSE)` and reports something related to pkgbuild. I am as confident as I dare be that this is not due to changes in my package source code, because I have been making minor changes to the package that yesterday passed CI, and right now doesn't even get the actual `devtools::check()` in the CI but stalls already at `devtools::install(upgrade_dependencies = FALSE)`  with the following error message:

```
Error in get0(oNam, envir = ns) : 
  lazy-load database '/usr/local/lib/R/site-library/pkgbuild/R/pkgbuild.rdb' is corrupt
Calls: <Anonymous> -> :: -> getExportedValue -> get0
In addition: Warning message:
In get0(oNam, envir = ns) : internal error -3 in R_decompress1
```

This didn't happen yesterday (worst argument ever, I know) - and locally my package passes `devtools::check()`.

After noticing that the pkgbuild 1.2.0 is as of very recent (yesterday?) I thought I might dare ask whether this error is related to the new release of pkgbuild.

If relevant, here are the steps of my CI:
```
jobs:
  build:
    runs-on: ubuntu-18.04
    container: docker://rocker/tidyverse
    steps:
    - uses: actions/checkout@v1
    - run: Rscript -e 'devtools::install_deps(".", dependencies=TRUE, upgrade=FALSE)'
    - run: Rscript -e 'devtools::build()'
    - run: Rscript -e 'devtools::install(upgrade_dependencies = FALSE)'
    - run: Rscript -e 'devtools::check()'
```

Thanks in advance for any feedback on this.

**Comment by amarquard** [comment]
To be more specific, it wasn't just yesterday that it worked. It was actually going fine past the `devtools::install(upgrade_dependencies = FALSE)` step a few hours ago, and now it's not... if that might help to clarify what has changed...

**Comment by amarquard** [comment]
Installing `pkgbuild` in a separate step that doesn't use `devtools` fixes this. So perhaps this is a `devtools` issue, not a `pkgbuild` issue?  (In that case my apologies for posting it here)

```
jobs:
  build:
    runs-on: ubuntu-18.04
    container: docker://rocker/tidyverse
    steps:
    - uses: actions/checkout@v1
    - run: Rscript -e 'devtools::install_deps(".", dependencies=TRUE, upgrade=FALSE)'
    - run: Rscript -e 'devtools::build()'
    - run: Rscript -e 'install.packages("pkgbuild")'
    - run: Rscript -e 'devtools::install(upgrade_dependencies = FALSE)'
    - run: Rscript -e 'devtools::check()'
```
